# Generated by Django 5.1.4 on 2024-12-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_course_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreplieshistory',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
