# Generated by Django 5.1.4 on 2024-12-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_commentreplieshistory_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='topics_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество тем'),
        ),
    ]
